spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://monorail.proxy.rlwy.net:23626/railway
    username: root
    password: ENC(M5dQuNz8tIYmu1sQ8NzKAysa8IgyXPdm8iKzVM+52gBDITUvkYRF535Iyw/Sw4na)
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: chiefbouncer@bossbouncer.io
    password: ENC(BfFwPJ+IFhwf8plHuqoAug4+XsMeEiqu)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jasypt:
  encryptor:
    password: ${encryptionKey:encryptionKey}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
app:
  reactDomain: https://bossbouncer.dev
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,https://boss-bouncer.vercel.app,https://bossbouncer.dev
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb2
    tokenExpirationMsec: 864000000