spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bossBouncer
    username: root
    password: ENC(0HZdtUIoTJof4RqWyvjd5UNN/dO3xVvH)
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: chiefbouncer@bossbouncer.io
    password: ENC(BfFwPJ+IFhwf8plHuqoAug4+XsMeEiqu)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jasypt:
  encryptor:
    password: ${encryptionKey:encryptionKey}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator