spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:18333/railway
    username: root
    password: ENC(HsYXxYKznX6sq+abSpbd+V1abAYVHDSLxOhx4TeqUaOYKuwuPV5fVzCbTCdhdBh8)
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
app:
  reactDomain: https://bossbouncer.com
  cors:
    allowedOrigins: https://www.bossbouncer.com