spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://monorail.proxy.rlwy.net:23626/railway
    username: root
    password: ENC(M5dQuNz8tIYmu1sQ8NzKAysa8IgyXPdm8iKzVM+52gBDITUvkYRF535Iyw/Sw4na)
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  reactDomain: https://bossbouncer.dev
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,https://boss-bouncer.vercel.app,https://www.bossbouncer.dev