spring:
  profiles:
    active: ${ENV:local}
  mail:
    host: smtp.office365.com
    port: 587
    username: chiefbouncer@bossbouncer.io
    password: ENC(BfFwPJ+IFhwf8plHuqoAug4+XsMeEiqu)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  reactDomain: https://boss-bouncer.vercel.app
  apiKey: REPORT_KEY
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb2
    tokenExpirationMsec: 900000
    otpExpirationMesc: 300000
jasypt:
  encryptor:
    password: ${encryptionKey:encryptionKey}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator