spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bossBouncer
    username: root
    password: Arya@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: chiefbouncer@bossbouncer.io
    password: AsdLkjQazPlm10&
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
